name: CI/CD Workflow

on:
  push:
    branches:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          make install-dependences

      - name: Build Dependences
        run: |
          make clean-all
          make build-limmat
          make build-limboole
          # Can't use make all directly...
          # Probably because git actions isn't exactly a terminal. 
      
      - name: Setup Server
        run: |
          set -x
          export TERM=xterm
          nohup php -S 127.0.0.1:8000 > server.log 2>&1 &

      - name: Run tests
        run: |
          echo "Testing connection..."
          for i in {1..10}; do
            curl -s 127.0.0.1:8000 > /dev/null && break
            echo "Waiting for server..."
            sleep 1
          done

          if ! curl -s 127.0.0.1:8000 > /dev/null; then
            echo "Error: Server did not respond after 10 attempts."
            exit 1
          fi

          echo "OK: Server is online!"
          
          # ./example_requests/default_request.sh

          # cat output.json

          python3 /.github/workflows/optimization_test.py

      - name: Deploy
        run: |
          echo "Deploying..."
