name: perf-evaluation

on:
  push:
    branches:
      - main
      - beta
      - stable-pr-branch
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          make install-dependences

      - name: Build Dependences
        run: |
          make clean-all
          make build-limmat
          make build-limboole
          # Can't use make all directly...
          # Probably because git actions isn't exactly a terminal. 
      
      - name: Setup Server
        run: |
          set -x
          export TERM=xterm
          nohup php -S 127.0.0.1:8000 > server.log 2>&1 &

      - name: Run tests
        run: |
          echo "Testing connection..."
          for i in {1..10}; do
            curl -s 127.0.0.1:8000 > /dev/null && break
            echo "Waiting for server..."
            sleep 1
          done

          if ! curl -s 127.0.0.1:8000 > /dev/null; then
            echo "Error: Server did not respond after 10 attempts."
            exit 1
          fi

          echo "OK: Server is online!"
          
          # ./example_requests/default_request.sh

          # cat output.json

          python3 .github/workflows/optimization_test.py

      - name: Upload time usage graph
        uses: actions/upload-artifact@v4
        with:
          name: time-usage-graph
          path: .github/workflows/data/time_usage.png

      - name: Comment on PR with graph artifact
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: "### 📊 Time Usage Graph\n"
                    + "You can download the graph artifact here: "
                    + "[Time Usage Graph Artifact](https://github.com/${{ github.repository }}/suites/${{ github.run_id }}/artifacts/0)"
            });

      - name: Deploy
        run: |
          echo "Deploying..."
